[package]
name = "lang"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
env_logger = "0.10.0"
log = "0.4.20"
macros = { path = "./macros"}
ntest = "0.9.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "repl"
path = "repl/main.rs"

[[bin]]
name = "cash"
path = "cash/main.rs"
